name: build-docs

permissions:
  contents: write
# Only run this when the master branch changes
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
      - '**.md'
      - 'pyproject.toml'
      - '**.py'
      - 'templates/**'
      - '.github/workflows/build-docs.yml'

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install --with=dev

    # Build the site
    - name: Build the site
      run: |
        poetry run pdoc --docformat numpy -o docs/ ./shop_scraper_hr

    # If we've pushed to master, push the book's HTML to github-pages
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
